services:
  nginx:
    container_name: qdca-nginx
    build: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
      - ./docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/html
    depends_on:
      - api
      
  api:
    container_name: qdca-api
    build: ./docker/php
    volumes:
      - ./html:/var/www/html

  db:
    container_name: qdca-db
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker-database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci && chmod 644 /etc/mysql/conf.d/my.cnf
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
      